version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  sixpack-participate:
    image: sixpack:1.0.3
    build:
      context: .
      dockerfile: Dockerfile-sixpack
    depends_on:
      - redis
    volumes:
      - ./:/sixpack/
    environment:
      SIXPACK_CONFIG: /sixpack/docker-config.yml
    ports:
      - "5000:5000"
    command:
      sh -c "/sixpack/bin/sixpack"

  sixpack-web:
    image: sixpack:1.0.3
    build:
      context: .
      dockerfile: Dockerfile-sixpack
    depends_on:
      - redis
    volumes:
      - ./:/sixpack/
    ports:
      - "8090:8090"
    environment:
      SIXPACK_CONFIG: /sixpack/docker-config.yml
      SIXPACK_WEB_PORT: 8090
    command: >
      sh -c "ls -al /sixpack \
        && python /sixpack/sixpack/test/seed \
        && /sixpack/bin/sixpack-web"
